# Generated by Django 4.2 on 2023-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_hours', '0002_overtime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='end_time',
            field=models.TimeField(default="12:30"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overtime',
            name='start_time',
            field=models.TimeField(default="12:30"),
            preserve_default=False,
        ),
    ]
