# Generated by Django 4.2.1 on 2023-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_hours', '0003_overtime_end_time_overtime_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overtime',
            name='sickness',
            field=models.BooleanField(default=False),
        ),
    ]
